[package]
name = "client"
version = "0.0.1"
authors = [
    "PJB3005 <pieterjan.briers@gmail.com>",
    "clusterfack <clusterfack@users.noreply.github.com>",
    "CrAzYPiLoT-SS13 <minima38123@gmail.com>"
]

workspace = "../"

[dependencies]
piston = "0.26.0"
piston2d-graphics = "0.19.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.36.0"
piston_window = "0.54.0"
shared = { path = "../shared" }
