[package]
name = "server"
version = "0.1.0"
authors = [
    "PJB3005 <pieterjan.briers@gmail.com>",
    "clusterfack <clusterfack@users.noreply.github.com>",
    "CrAzYPiLoT-SS13 <minima38123@gmail.com>"
]

workspace = "../"

[dependencies]
shared = { path = "../shared" }
